# Generated by Django 5.0 on 2024-01-01 19:37

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.ImageField(blank=True, height_field=400, upload_to=users.models.user_directory_path, width_field=400),
        ),
    ]
