# Generated by Django 5.0 on 2024-01-01 20:07

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(default='acolotltd', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ImageField(blank=True, upload_to=users.models.user_directory_path),
        ),
    ]
