# Generated by Django 5.0 on 2024-01-07 11:42

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_alias_alter_user_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='des',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pic',
        ),
        migrations.AddField(
            model_name='profile',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, upload_to=users.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(default='software developer', max_length=128),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
