# Generated by Django 5.0 on 2024-01-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_des_remove_user_pic_profile_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.BooleanField(default=False),
        ),
    ]
