# Generated by Django 5.0 on 2024-01-13 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_media_type', to='socials.mediatype', to_field='name'),
        ),
        migrations.AlterField(
            model_name='mediatype',
            name='icon',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='mediatype',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='mediatype',
            name='url',
            field=models.URLField(max_length=30, unique=True),
        ),
    ]
