# Generated by Django 5.0 on 2024-01-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0002_alter_media_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='socials',
            field=models.ManyToManyField(blank=True, related_name='user_social_media', to='socials.media'),
        ),
    ]
